---
title: Stackbit Fjord Theme
baseURL: "/"
params:
  palette: yellow
  header:
    title: Demo Page for lab homepage
    tagline: Minimal and clean blog theme
    logo_img: "/images/アセット 1.svg"
    bg_img: "/images/IMG_6096_x0,5.jpeg"
    has_nav: true
    has_social: true
  footer:
    content: "&copy; All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
